name: Build and publish package

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  release:
    types: [published]
    tags:
    - "v*.*.*"
  workflow_dispatch:
    inputs:
      version:
        description: "The version of the package with the following syntax: x.x.x"
        required: true

permissions: write-all

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      NUGET_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
         
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x.x'
         
      - name: Authenticate to github packages
        run: dotnet nuget add source ${{env.NUGET_URL}} -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text -n github -u ${{ github.repository_owner }}
         
      - name: Obtain VERSION variable from tag if the workflow was started on release
        if: ${{github.event_name == 'release'}}
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> "$GITHUB_ENV"
      
      - name: Obtain VERSION variable from tag if the workflow was started manually
        if: ${{github.event_name == 'workflow_dispatch'}}
        run: echo "VERSION=${{ github.event.inputs.version }}" >> "$GITHUB_ENV"
           
      - name: Build
        run: dotnet build -c Release /p:Version=${{env.VERSION}}
         
      - name: Generate a NuGet package
        run: dotnet pack -c Release /p:Version=${{env.VERSION}} --no-build -o .
        
      - name: Push to GitHub package registry
        run: dotnet nuget push *.nupkg -k ${{ secrets.GITHUB_TOKEN }} -s ${{env.NUGET_URL}}
